### ISSUE TITLE
Installing as a package breaks shader #include

### ISSUE THREAD

**Issue by HG-Dev** [Toorah/com.toorah-games.gradienttool#1]
Installing the gradient tool as a package places its files in a destination from which the `#include "Assets/com.toorah-games.gradienttool/Editor/Gradient.cginc"` line in GradientEditor.shader sadly no longer applies.

Some quick testing shows that the directory portion of the #include could be safely removed.
`#include "Gradient.cginc"`

**Comment by Toorah** [comment]
Using AmplifyShader Editor to link CGInc files automatically uses the entire file path, I manually edited the file now
